services:
  db:
    image: postgres:16
    container_name: crm_remax_db
    environment:
      POSTGRES_DB: crm
      POSTGRES_USER: crm
      POSTGRES_PASSWORD: crm123
    ports:
      - "5432:5432"
    volumes:
      - crm_pgdata:/var/lib/postgresql/data
volumes:
  crm_pgdata:
